---
- name: c/c++/... installation
  become: yes
  block:

  - name: Install clang-17
    ansible.builtin.apt:
      state: present
      pkg:
      - clang
      - clang-17
      - llvm
      install_recommends: yes

