---
- name: c/c++/... installation
  become: yes
  block:

  - name: Install clang-12
    ansible.builtin.apt:
      state: present
      pkg:
      - clang
      - clang-12
      - llvm 
      install_recommends: yes

