---
- name: Download the chrome package
  become: no
  ansible.builtin.get_url:
    dest: ~/Downloads/chrome.deb
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  register: chrome_download

- name: Install the chrome package
  become: yes
  ansible.builtin.apt:
    deb: "{{ chrome_download.dest }}"
  ignore_errors: yes

