---
- name: ebpf tasks
  become: no
  block:

  - name: get uname -r
    ansible.builtin.shell: uname -r
    register: uname_minus_r

  - name: Output uname -r
    ansible.builtin.debug:
      msg: uname -r is '{{ uname_minus_r.stdout }}'

  # See https://apt.llvm.org/
  - name: Install llvm using the installation script
    block:

    - name: Download llvm.sh
      ansible.builtin.get_url:
        url: https://apt.llvm.org/llvm.sh
        mode: '0755'
        dest: ~/Downloads/llvm.sh
        force: yes
      register: llvm_sh

    - name: Output llvm.sh location
      ansible.builtin.debug:
        msg: "llvm.sh -> {{ llvm_sh.dest }}"

    - name: Run llvm.sh
      ansible.builtin.expect:
        command: "{{ llvm_sh.dest }} {{ llvm_version }}"
        responses:
          'Press \[ENTER\] to continue or Ctrl\-c to cancel.': ''
      become: yes

    - name: Set default llvm llvm_version links
      ansible.builtin.shell:
        chdir: /usr/lib/llvm-{{ llvm_version }}/bin
        cmd: for f in *; do rm -f /usr/bin/$f; ln -s ../lib/llvm-{{ llvm_version }}/bin/$f /usr/bin/$f; done
      become: yes

  - name: Get linux source
    ansible.builtin.apt:
      update_cache: yes
      pkg: linux-source
    become: yes

  # https://docs.cilium.io/en/latest/bpf/toolchain/#development-environment
  - name: Install ebpf required packages
    become: yes
    ansible.builtin.apt:
      pkg:
        - wget
        - build-essential
        - software-properties-common
        - lsb-release
        - libelf-dev
        - linux-headers-generic
        - pkg-config
        - libpolly-{{ llvm_version }}-dev
        - iproute2
