---
- name: Install Dev tools
  block:

  - name: Images
    ansible.builtin.apt:
      pkg:
      - gimp

  - name: java
    ansible.builtin.apt:
      pkg:
      - openjdk-18-jdk
      - maven
      - gradle

  - name: python
    ansible.builtin.apt:
      pkg:
      - python3

  - name: rust
    ansible.builtin.import_tasks: rust.yaml

  - name: go
    ansible.builtin.import_tasks: go.yaml
