---
- name: Install Dev tools
  become: yes
  block:

  - name: Images
    ansible.builtin.apt:
      pkg:
      - gimp

  - name: java
    ansible.builtin.apt:
      pkg:
      - openjdk-21-jdk
      - maven
      - gradle

  - name: python
    ansible.builtin.apt:
      pkg:
      - python3
      - python3-pip

  - name: rust
    ansible.builtin.import_tasks: rust.yaml

  - name: go
    ansible.builtin.import_tasks: go.yaml

  - name: c/c++/etc...
    ansible.builtin.import_tasks: c-etc.yaml

  - name: node
    ansible.builtin.import_tasks: node.yaml

  - name: zig
    ansible.builtin.import_tasks: zig.yaml

