---
- name: Download dropbox
  become: no
  ansible.builtin.get_url:
    dest: ~/Downloads/dropbox.deb
    url: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2020.03.04_amd64.deb
    force: true
  register: dropbox_result

- name: Install dropbox
  become: yes
  ansible.builtin.apt:
    deb: "{{ dropbox_result.dest }}"

