---
- name: ebpf tasks
  become: no
  block:

  - name: get uname -r
    ansible.builtin.shell: uname -r
    register: uname_minus_r

  - name: Output uname -r
    ansible.builtin.debug:
      msg: uname -r is '{{ uname_minus_r.stdout }}'

  # See https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---source and
  #     https://github.com/georgenicoll/xdp-tutorial/blob/master/setup_dependencies.org
  - name: Install ebpf packages
    become: yes
    ansible.builtin.apt:
      pkg:
      - zip
      - bison
      - build-essential
      - cmake
      - flex
      - git
      - clang
      - llvm
      - gcc-multilib
      - libcap-dev
      - libedit-dev
      - libllvm14
      - libclang-14-dev
      - python3
      - zlib1g-dev
      - libelf-dev
      - libfl-dev
      - python3-setuptools
      - liblzma-dev
      - libdebuginfod-dev
      - arping
      - netperf
      - iperf
      - libbpf-dev
      - linux-tools-{{ uname_minus_r.stdout }}
      - linux-headers-{{ uname_minus_r.stdout }}
      - linux-tools-common
      - linux-tools-generic
      - linux-cloud-tools-generic
      - tcpdump

  - name: get bcc git repo
    ansible.builtin.git:
      repo: https://github.com/iovisor/bcc.git
      dest: git/bcc
      clone: yes
      update: yes
      version: master

  - name: make build directory
    ansible.builtin.file:
      path: git/bcc/build
      state: directory

  - name: build bcc (1)
    ansible.builtin.shell:
      chdir: git/bcc/build
      cmd: cmake ..

  - name: build bcc (2)
    ansible.builtin.shell:
      chdir: git/bcc/build
      cmd: make

  - name: install bcc
    become: yes
    ansible.builtin.shell:
      chdir: git/bcc/build
      cmd: make install

  - name: make python 3 binding (1)
    ansible.builtin.shell:
      chdir: git/bcc/build
      cmd: cmake -DPYTHON_CMD=python3 ..

  - name: make python 3 binding (2)
    ansible.builtin.shell:
      chdir: git/bcc/build/src/python
      cmd: make

  - name: install python 3 binding
    become: yes
    ansible.builtin.shell:
      chdir: git/bcc/build/src/python
      cmd: make install

  - name: get bpftool git repo
    ansible.builtin.git:
      repo: https://github.com/libbpf/bpftool.git
      dest: git/bpftool
      clone: yes
      update: yes
      recursive: true
      version: master

  - name: build bpftool
    ansible.builtin.shell:
      chdir: git/bpftool/src
      cmd: make -j$(nproc)

  - name: install bpftool
    become: yes
    ansible.builtin.shell:
      chdir: git/bpftool/src
      cmd: make install

  - name: bpftrace
    ansible.builtin.import_tasks: bpftrace.yaml

  - name: remove bpftool gitrepo
    ansible.builtin.file:
      path: git/bpftool
      state: absent

  - name: remove bcc gitrepo
    ansible.builtin.file:
      path: git/bcc
      state: absent
