---
- name: Nix Install Apps
  become: false
  block:

  - name: Output Item
    ansible.builtin.debug:
      var: item
  - name: Installing {{ item }}
    ansible.builtin.shell: NIXPKGS_ALLOW_UNFREE=1 nix-env -iA {{ item }}

