---
- name: Obsidian installation steps
  become: no
  vars:
    obsidian_github_api_endpoint: "https://api.github.com/repos/obsidianmd/obsidian-releases/releases/latest"
  block:

  - name: Get home directory
    ansible.builtin.shell:
      cmd: echo "$(dirname ~)/$(basename ~)"
    register: home_dir

  - name: Output home directory
    ansible.builtin.debug:
      msg: Home directory is {{ home_dir.stdout }}

  - name: Get latest obsidian release version from gitlab
    ansible.builtin.shell:
      cmd: curl --silent "{{ obsidian_github_api_endpoint }}" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'
    register: obsidian_version

  - name: Output obsidian version
    ansible.builtin.debug:
      msg: Latest obsidian version is {{ obsidian_version.stdout }}

  - name: Download obsidian deb
    ansible.builtin.get_url:
      url: "https://github.com/obsidianmd/obsidian-releases/releases/download/{{ obsidian_version.stdout }}/obsidian_{{ obsidian_version.stdout | replace('v', '') }}_amd64.deb"
      dest: "{{ home_dir.stdout }}/Downloads/obsidian_{{ obsidian_version.stdout }}.deb"
      force: true

  - name: Install Obsidian
    become: yes
    ansible.builtin.apt:
      deb: "{{ home_dir.stdout }}/Downloads/obsidian_{{ obsidian_version.stdout }}.deb"
