# All tasks here expect become: yes
---
- name: Python and modules
  become: yes
  block:

  # deadsnake not needed anymore
  #- name: Add deadsnake ppa repo
  #  ansible.builtin.apt_repository:
  #    repo: ppa:deadsnakes/ppa
  #    update_cache: yes

  - name: Install packages
    ansible.builtin.apt:
      state: present
      pkg:
        - python3
        - python3.11
        - python3.12
        - python3.12-full
        - jq
        - yq

  # yq now comes from apt
  #- name: Install yq
  #  ansible.builtin.pip:
  #    name: yq
