# All tasks here expect become: yes
---
- name: Python and modules
  become: yes
  block:

  - name: Add deadsnake ppa repo
    ansible.builtin.apt_repository:
      repo: ppa:deadsnakes/ppa
      update_cache: yes

  - name: Install packages
    ansible.builtin.apt:
      state: present
      pkg:
        - python3
        - python3.11
        - python3.12
        - jq

  - name: Install yq
    ansible.builtin.pip:
      name: yq
