---
- hosts: localhost
  gather_facts: no
  become: yes

  tasks:

  - name: Install Ubuntu Packages
    ansible.builtin.import_tasks: ubuntu-packages.yaml

  - name: Install obsidian
    ansible.builtin.import_tasks: obsidian.yaml

  - name: Install nix and nix packages
    ansible.builtin.import_tasks: nix.yaml

  - name: Install utilites to access this remotely
    ansible.builtin.import_tasks: remote-access.yaml

  - name: Install vscode
    ansible.builtin.import_tasks: vscode.yaml

  # - name: Install Citrix
  #   ansible.builtin.import_tasks: citrix.yaml

  # Teams now a PWA
  # - name: Install Teams
  #   ansible.builtin.import_tasks: teams.yaml

  - name: Install VPN
    ansible.builtin.import_tasks: vpn.yaml

  - name: Install Zoom
    ansible.builtin.import_tasks: zoom.yaml

  - name: Install Chrome
    ansible.builtin.import_tasks: chrome.yaml

  - name: Install Dropbox
    ansible.builtin.import_tasks: dropbox.yaml

  - name: Install Dev Tools
    ansible.builtin.import_tasks: dev.yaml

  - name: Install Docker
    ansible.builtin.import_tasks: docker.yaml

  - name: Install k8s Tools
    ansible.builtin.import_tasks: k8s.yaml

  - name: Install vagrant
    ansible.builtin.import_tasks: vagrant.yaml

  - name: Install virtualization tools
    ansible.builtin.import_tasks: virtualization.yaml

  - name: Install epbf Tools
    ansible.builtin.import_tasks: ebpf.yaml
