# All tasks here expect become: yes
---
- name: Perform initial housekeeping
  block:
  - name: apt update, clean And upgrade
    ansible.builtin.apt:
      autoclean: yes
      #clean: yes
      update-cache: yes
      upgrade: yes
  - name: Reduce snap retention
    ansible.builtin.shell: snap set system refresh.retain=2
  - name: Run snap cleanup
    ansible.builtin.script: scripts/snap-cleanup.sh
    args:
      executable: bash      

- name: Remove packages
  ansible.builtin.apt:
    state: absent
    pkg:
    - chromium-browser
    - firefox

- name: Install packages
  ansible.builtin.apt:
    state: present
    pkg:
    - vim
    - fzf
    - keepassxc
    - curl
    - pavucontrol
    - openssh-server
    - ansible
    - ansible-lint
    - linux-tools-common
    - linux-tools-generic
    - gnome-pie
    - inetutils-traceroute
    - htop
