---
- name: Update And Upgrade
  ansible.builtin.apt:
    update-cache: yes
    upgrade: yes

- name: Install packages
  ansible.builtin.apt:
    state: present
    pkg:
    - vim
    - fzf
    - keepassxc
    - curl
    - pavucontrol
    - openssh-server
    - ansible
    - ansible-lint
    - linux-tools-common
    - linux-tools-generic
    - gnome-pie
    - inetutils-traceroute
    - htop

- name: Remove packages
  ansible.builtin.apt:
    state: absent
    pkg:
    - chromium-browser
    - firefox 

