---
- name: Update And Upgrade
  ansible.builtin.apt:
    update-cache: yes
    upgrade: yes

- name: Install packages
  ansible.builtin.apt:
    state: present
    pkg:
    - vim
    - fzf
    - keepassxc
    - curl
    - pavucontrol
    - openssh-server
    - ansible
    - ansible-lint

- name: Remove packages
  ansible.builtin.apt:
    state: absent
    pkg:
    - chromium-browser
    - firefox 

