---
- name: Get Code deb
  become: no
  ansible.builtin.get_url:
    url: https://update.code.visualstudio.com/latest/linux-deb-x64/stable
    dest: ~/Downloads/vscode.latest.deb
    force: yes
  register: vscode

- name: Downloaded vscode File
  ansible.builtin.debug:
    msg: "Downloaded to {{ vscode.dest }}"

- name: Install vscode
  ansible.builtin.apt:
    deb: "{{ vscode.dest }}"

